In [1]:
import pandas as pd

In [20]:
df = pd.read_csv('POStagger/DataSiapPOS.csv', index_col=0)
df2 = pd.read_csv('POStagger/readytfidf3.csv')
df2['Status'] = df2['Status'].replace(['Positif','Negatif','Netral'],['0','1','2'])
df2['Status']

0       0
1       0
2       0
3       0
4       0
       ..
1532    2
1533    2
1534    2
1535    2
1536    2
Name: Status, Length: 1537, dtype: object

In [21]:
df

,hijau,cuan,kuat,cerah,tp,haka,beli,jebol,profit,naik,...,semoga,ketat,force,exdate,mentok,pantul,aggresive,galau,inflasi,gas
0,0.462232,0.732612,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.379493,0.000000,0.411972,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.000000,0.426429,0.000000,0.374383,0.416878,0.0,0.000000,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,0.000000,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.112797,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1532,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,...,0.276705,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1533,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1534,0.000000,0.000000,0.000000,0.000000,0.531618,0.0,0.000000,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1535,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1536,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0